DROP TABLE IF EXISTS CMRC_Reviews;
GO
DROP TABLE IF EXISTS CMRC_ShoppingCart;
GO
DROP TABLE IF EXISTS CMRC_Products;
GO
DROP TABLE IF EXISTS CMRC_Categories;
GO
DROP TABLE IF EXISTS CMRC_OrderDetails;
GO
DROP TABLE IF EXISTS CMRC_Orders;
GO
DROP TABLE IF EXISTS CMRC_Customers;
GO